### PR TITLE
Maven plugin fixes

### LINKED ISSUE #270: `NullPointerException` when using 0.9.12 and later to run tests with native image compilation
**Describe the bug**
Running a simple test with `native-maven-plugin` 0.9.12 and later is resulting a `NullPointerException` at build time. 

**To Reproduce**
Reproduce: https://github.com/mpeddada1/junit-testrule

**Expected behavior**
The tests run successfully with the versions in question.

**Logs**
Following the steps in the README of the reproducer is resulting in this stacktrace:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.MySampleTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 s - in com.example.MySampleTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- native-maven-plugin:0.9.13:test (test-native) @ child-project ---
[INFO] ====================
[INFO] Initializing project: child-project
[INFO] ====================
[INFO] Found GraalVM installation from JAVA_HOME variable.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.770 s
[INFO] Finished at: 2022-07-20T17:43:43-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.13:test (test-native) on project child-project: Execution test-native of goal org.graalvm.buildtools:native-maven-plugin:0.9.13:test failed.: NullPointerException -> [Help 1]
```
[Snippet of stacktrace with -X flag ](https://gist.github.com/mpeddada1/9b145382933c837489ec8d1aa56e3cc9)

However, **note** that this test runs successfully with `0.9.11`

**System Info (please complete the following information):**
 - OS: `Linux`
 - GraalVM Version: 22.1.0 CE
 - Java Version: 11
 - Plugin version: native-maven-plugin 0.9.12 and 0.9.13

I'm wondering if anyone has run into this problem? Thank you!

cc @suztomo @meltsufin

### PR DESCRIPTION
**Pull request by lazar-mitrovic**
Allow running native:build from the command-line #273
NullPointerException fix #270

### CODE REVIEW

File: native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildNoForkMojo.java [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+import org.codehaus.plexus.component.configurator.expression.ExpressionEvaluationException;
+import org.codehaus.plexus.util.xml.Xpp3Dom;
+
+import java.util.Arrays;
+import java.util.List;
+import java.util.function.BiFunction;
+
+
+/**
+ * This goal runs native tests. It functions the same as the native:build goal, but it
```
Comment (snicoll) [inline native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildNoForkMojo.java:63]: is "This goal runs native tests" accurate?

**Review by snicoll — COMMENTED** [review]
Thanks for the quick turnaround!

File: native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildNoForkMojo.java (hunk 1 above)
Comment (lazar-mitrovic) [reply native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildNoForkMojo.java:63]: Yep that is a mistake (copied and pasted from the test mojo), thanks for noticing!

File: native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildMojo.java [hunk 2]
```diff
@@ -41,114 +41,21 @@
...
-    private void maybeSetMainClassFromPlugin(BiFunction<String, String[], String> mainClassProvider, String pluginName, String... nodeNames) {
-        if (mainClass == null) {
-            mainClass = mainClassProvider.apply(pluginName, nodeNames);
-
-            if (mainClass != null) {
-                getLog().info("Obtained main class from plugin " + pluginName + " with the following path: " + String.join(" -> ", nodeNames));
-            }
-        }
-    }
+@Execute(phase = LifecyclePhase.COMPILE)
```
Comment (lazar-mitrovic) [inline native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildMojo.java:57]: @snicoll This works in my testing but I'm not sure if this is a correct thing to do.
Are there cases where resources / additional code is added after the COMPILE phase?

I didn't want to execute PACKAGE phase here since I cannot prevent it from building native-image twice.

Comment (snicoll) [reply native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeBuildMojo.java:57]: Compile won't work as it wouldn't have produced the `jar` that NBT requires by default. It should be `package`. 

> I didn't want to execute PACKAGE phase here since I cannot prevent it from building native-image twice.

That's exactly what the `no-fork` variant is for.

**Comment by alvarosanchez** [comment]
I don't see this working. The default configuration is already binding `native:build` to the package phase:

```xml
<execution>
  <id>build-native</id>
  <goals>
    <goal>build</goal>
  </goals>
  <phase>package</phase>
</execution>
```

With the above and `@Execute(phase = LifecyclePhase.PACKAGE)`, the package phase will run twice.

**Comment by snicoll** [comment]
Yes. That's exactly what the "no-fork" goal is all about. I am afraid this is a limitation in Maven and nothing we can do about it.

**Comment by alvarosanchez** [comment]
But then, this is a breaking change. `native:build` should be left without forking, and then another goal (e.g. `native:build-package`) should be added with the `@Execute` annotation.

**Comment by snicoll** [comment]
As I've said in my opening comment that's what core maven plugins do. Yes it's a breaking change but that's ok imo given the benefit. 

The obvious goal to use on the command line is "build" not "build-and-package" or something. 

This isn't the first time breaking changes were made pre-1.0 for the benefit of the community.

**Comment by alvarosanchez** [comment]
Since the version is still 0.9.x, I guess it's ok to break things.

However, documentation needs to reflect this, and the breaking change needs to be made clear in the release notes.

**Comment by lazar-mitrovic** [comment]
- [ ] Change samples and docs before merging this PR

**Comment by snicoll** [comment]
@lazar-mitrovic I don't think a parity for the test mojo is warranted. Contrary to other core plugins, the surefire plugin does not execute the test phase. This change would mean that users having an execution should move to the no-fork variant. 

Can we please consider doing this change for the `build` goal only?

File: native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeTestMojo.java [hunk 3]
```diff
@@ -70,7 +70,8 @@
 import static org.graalvm.buildtools.Utils.NATIVE_TESTS_EXE;
 
 /**
- * @author Sebastien Deleuze
+ * This goal runs native tests. It functions the same as the native:test goal, but it
+ * does not fork the build, so it is suitable for attaching to the build lifecycle.
```
Comment (snicoll) [inline native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeTestMojo.java:74]: I think that's outdated now.

**Review by snicoll — COMMENTED** [review]
Thanks for the update!

File: native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeCompileMojo.java [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+ * This goal builds native images.
+ * It can be invoked using `mvn native:compile`.
+ */
+@Mojo(name = "compile", defaultPhase = LifecyclePhase.PACKAGE,
+        requiresDependencyResolution = ResolutionScope.RUNTIME,
+        requiresDependencyCollection = ResolutionScope.RUNTIME)
+@Execute(phase = LifecyclePhase.PACKAGE)
+@SuppressWarnings("unused")
+public class NativeCompileMojo extends NativeCompileNoForkMojo {
+    // no-op
```
Comment (snicoll) [inline native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeCompileMojo.java:60]: A bit odd... What does "no-op" mean here?

File: native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeCompileMojo.java [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+
+import org.apache.maven.plugins.annotations.Execute;
+import org.apache.maven.plugins.annotations.LifecyclePhase;
+import org.apache.maven.plugins.annotations.Mojo;
+import org.apache.maven.plugins.annotations.ResolutionScope;
+
+
+/**
+ * This goal builds native images.
+ * It can be invoked using `mvn native:compile`.
```
Comment (snicoll) [inline native-maven-plugin/src/main/java/org/graalvm/buildtools/maven/NativeCompileMojo.java:52]: Perhaps worth clarifying that it is meant to be invoked on the command-line as a single goal or something. You're doing it already but the command-line bit isn't explicit.
